/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_goo_test_Activity_MyInfo_OpenCV */

#ifndef _Included_com_example_goo_test_Activity_MyInfo_OpenCV
#define _Included_com_example_goo_test_Activity_MyInfo_OpenCV
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_goo_test_Activity_MyInfo_OpenCV_PERMISSIONS_REQUEST_CODE
#define com_example_goo_test_Activity_MyInfo_OpenCV_PERMISSIONS_REQUEST_CODE 1000L


JNIEXPORT jlong JNICALL Java_com_example_goo_test_Activity_MyInfo_OpenCV_loadCascade
        (JNIEnv *, jobject, jstring);


JNIEXPORT void JNICALL Java_com_example_goo_test_Activity_MyInfo_OpenCV_detect
        (JNIEnv *, jobject, jlong, jlong, jlong, jlong);
#ifdef __cplusplus
}
#endif
#endif
